"""Execution implementations provide authoritative idempotency lookup and stop evidence."""

from typing import Protocol

from roboweaver.contracts import ActionRecord, ExecutionSnapshot, Observation


class Executor(Protocol):
    async def submit(self, action: ActionRecord) -> ExecutionSnapshot: ...
    async def lookup(self, idempotency_key: str) -> ExecutionSnapshot | None: ...
    async def cancel(self, idempotency_key: str) -> ExecutionSnapshot: ...
    async def observe(self) -> Observation: ...
